#!/bin/bash

#https://wiki.archlinux.org/index.php/Install_from_Existing_Linux

ARCH=i686
mkdir /tmp/archlinux
cd /tmp/archlinux

alias wget='wget --trust-server-names'

wget http://www.archlinux.org/packages/core/$ARCH/pacman/download/
wget http://www.archlinux.org/packages/core/any/pacman-mirrorlist/download/

wget http://www.archlinux.org/packages/core/$ARCH/libfetch/download/
wget http://www.archlinux.org/packages/core/$ARCH/libarchive/download/
wget http://www.archlinux.org/packages/core/$ARCH/openssl/download/
wget http://www.archlinux.org/packages/core/$ARCH/xz/download/
wget http://www.archlinux.org/packages/core/$ARCH/expat/download/

for f in *.tar.gz ; do tar xzvf $f ; done

export PATH=/tmp/archlinux/usr/bin:$PATH
export LD_LIBRARY_PATH=/tmp/archlinux/usr/lib:$LD_LIBRARY_PATH
alias pacman="pacman --config /tmp/archlinux/etc/pacman.conf"

cd /
for f in /tmp/archlinux/pacman-*pkg.tar.gz ; do
  tar xzf $f
done

#needs fdisk first
mkfs.ext3 /dev/sda1
mkfs.ext3 -j -O dir_index /dev/sda1 

mkreiserfs /dev/sdxx 

mkswap /dev/sda2
swapon /dev/sda2

mkdir /newarch 
mount /dev/sda1 /newarch

mkdir -p /newarch/var/lib/pacman 
pacman -Sy -r /newarch

pacman --cachedir /newarch/var/cache/pacman/pkg -S base -r /newarch

cd /newarch/dev 
rm console ; mknod -m 600 console c 5 1 
rm null ; mknod -m 666 null c 1 3 
rm zero ; mknod -m 666 zero c 1 5

cp /etc/resolv.conf /newarch/etc/ 

mount -t proc proc /newarch/proc
mount -t sysfs sys /newarch/sys
mount -o bind /dev /newarch/dev

chroot /newroot pacman -S kernel26