Veewee::Session.declare({
  :cpu_count => '1',
  :memory_size => '512',
  :disk_size => '20480',
  :disk_format => 'VDI',
  :hostiocache => 'off',
  :os_type_id => 'Debian_64',
  :iso_file => "kali-linux-1.0.9a-amd64.iso",
  :iso_src => "http://cdimage.kali.org/kali-1.0.9a/kali-linux-1.0.9a-amd64.iso",
  :iso_md5 => "401e2b14921de5f808c7786b3b84dc57",
  :iso_download_timeout => "2000",
  :boot_wait => "10",
  :boot_cmd_sequence => [
     '<Esc>',
     'install ',
     'preseed/url=http://%IP%:%PORT%/preseed.cfg ',
     'debian-installer=en_US ',
     'auto ',
     'locale=en_US ',
     'kbd-chooser/method=us ',
     'netcfg/get_hostname=%NAME% ',
     'netcfg/get_domain=vagrantup.com ',
     'fb=false ',
     'debconf/frontend=noninteractive ',
     'console-setup/ask_detect=false ',
     'console-keymaps-at/keymap=us ',
     'keyboard-configuration/xkb-keymap=us ',
     '<Enter>'
  ],  
  :kickstart_port => "7122",
  :kickstart_timeout => "10000",
  :kickstart_file => "preseed.cfg",
  :ssh_login_timeout => "10000",
  :ssh_user => "vagrant",
  :ssh_password => "vagrant",
  :ssh_key => "",
  :ssh_host_port => "7222",
  :ssh_guest_port => "22",
  :sudo_cmd => "echo '%p'|sudo -S bash '%f'",
  :shutdown_cmd => "halt -h -p",
  :postinstall_files => [
    "base.sh",
    "virtualbox.sh",
    "vagrant.sh",
    "chef.sh",
    "puppet.sh",
    "cleanup.sh",
    "zerodisk.sh"
  ],
  :postinstall_timeout => "10000"
})
